### PR TITLE
add files for npm

### PR DESCRIPTION
**Pull request by bradtwurst**
npm package.json and .npmignore to assist in publishing npm package

 Update npm package version #97

### CODE REVIEW

**Comment by jaapz** [comment]
Please merge this. Currently we can already install this package using @bradtwurst's repo like this:

    npm install github:bradwurst/weather_icons#npm_package

But that is not an optimal solution. Would be great to officially have this package on npm.

**Comment by Apercu** [comment]
Would love to see this merged too.

**Comment by jaapz** [comment]
Maybe we'll get @erikflowers attention when we ping him :)

**Comment by erikflowers** [comment]
Do I need to have access to update this page: https://www.npmjs.com/package/weather-icons ?

**Comment by Apercu** [comment]
Yes you do, I emailed @tbranyen and gave him your email so he can transfer you the ownership

**Comment by erikflowers** [comment]
I merged the request. I will wait to see if he emails. I think I contacted him before with no response. 



On November 26, 2015 at 7:25:50 AM PST, Balthazar Gronon <notifications@github.com> wrote:Yes you do, I emailed @tbranyen and gave him your email so he can transfer you the ownership  —Reply to this email directly or view it on GitHub.

**Comment by Apercu** [comment]
@erikflowers Could you please give me your npm username?

**Comment by erikflowers** [comment]
It is erikflowers like on github. I just created it. 



On November 27, 2015 at 4:44:45 AM PST, Balthazar Gronon <notifications@github.com> wrote:@erikflowers Could you please give me your npm username?  —Reply to this email directly or view it on GitHub.

**Comment by d2s** [comment]
User account page on https://www.npmjs.com/~erikflowers is still missing the [`weather-icons`](https://www.npmjs.com/package/weather-icons) package as @tbranyen has forgotten to add you to the list of collaborators for the package at the npm registry.

**Pull request merged**
