### PR TITLE
Lookups for WMO4680, Yahoo! and Forecast.io

### PR DESCRIPTION
**Pull request by chk1**
I added LESS/CSS variable names with weather condition codes according to [World Meteorological Organization's code manual](http://www.wmo.int/pages/prog/www/WMOCodes/WMO306_vI1/VolumeI.1.html) used in weather stations and also the [Yahoo API codes](https://developer.yahoo.com/weather/documentation.html#codes) made by @aphillipo in #18. Also related #24 #7.
The WMO code associations done by me are approximations, I couldn't find 100% fitting icons on some codes. For example codes 00 ("No significant weather observed") and 02 ("State of sky on the whole unchanged during the past hour"), and also some of the gradients (light/medium/heavy rain).

I put them in separate files so that they can be easily commented out if you wish to compile a file without them, or only require a subset of (this project's) weather icons names OR Yahoo OR WMO4680.

I'm a LESS novice so there's probably a better way to name or generate them. 

I also added two test tables for Yahoo & WMO4860 codes with their respective descriptions, and a Windows .bat script for quick compiling.

Screenshot list Yahoo:

screen shot 2015-01-23 at 19 42 34yahoo

Screenshot list WMO:

screen shot 2015-01-23 at 19 42 40wmo

### CODE REVIEW

**Comment by chk1** [comment]
Added [Forecast.io](https://developer.forecast.io/docs/v2) too

weather-icons-forecastio

**Comment by erikflowers** [comment]
That's really cool. I do want to start working on including stylesheets for these specifical service weather codes, I just need to develop a good way to maintain it and have it be "plug and play" with my core build variables and classes so everything runs off the master sheet. I figure I just need to take a few days to focus on it hard so my Less compiling outputs the core sheet, and then the service specific ones without having to think about those.

**Comment by sul4bh** [comment]
This is awesome. Please consider adding this feature in the next release.

**Comment by sul4bh** [comment]
@chk1 do you have the code to icon mapping in a dictionary format(Python, PHP, Java, CVS)? I am interested in YQL code to icon mappings.

**Comment by sul4bh** [comment]
@chk1 nvm. Found here: https://github.com/erikflowers/weather-icons/pull/18

**Comment by erikflowers** [comment]
I will be adding this in the 2.0 which I have started working on. I will retrieve the files manually and work them in there as the new refactor is going to pretty much change the whole structure of the source.

**Comment by erikflowers** [comment]
Yahoo, WMO, and Forecast.io codes have been added to the 2.0-wip!

**Comment by chk1** [comment]
Sounds great, thanks for the update!

**Comment by sul4bh** [comment]
Thanks man.

**Pull request closed without merging**
