### PR TITLE
add woff2 font (37k)

### PR DESCRIPTION
**Pull request by martinlindhe**
Created a woff2 version of the font, based on the .woff version, using https://everythingfonts.com/woff-to-woff2

woff2 is a newer and smaller font format, supported by recent versions of Chrome and Firefox: http://caniuse.com/#feat=woff2

### CODE REVIEW

**Comment by erikflowers** [comment]
I can add the woff2. I will need to create it out of Fontsquirrel and test it out and add it to the stack. Where did you make this file?

**Comment by martinlindhe** [comment]
I created the woff2 font using this online conversion tool: https://everythingfonts.com/woff-to-woff2

**Comment by erikflowers** [comment]
There's a conflict here but I will be refactoring it all for 2.0 so I am going to add this there.

**Comment by erikflowers** [comment]
Woff2 has been added to the 2.0-wip

**Pull request closed without merging**
