### PR TITLE
Added support for Sass.

### PR DESCRIPTION
**Pull request by LasseHaslev**
Added support for Sass, changed variables for DRY coding and created mixins for simplifying code.
If you should add more icons, all you have to do is add it to the variables file and you are all set to compile the code :)

### CODE REVIEW

**Comment by erikflowers** [comment]
That looks way better than I do it. I do all the meticulous Less file updating one by one, with no loops or automation. Maybe I can figure out how to do something similar with Less as well.

**Comment by LasseHaslev** [comment]
Yes, i think this approach also could be possible in Less. :)
I forgot to add the font-face and the class for the icon to the output css. But created a new commit and this class should be good to go :)

**Comment by LasseHaslev** [comment]
When are you merging these changes?

**Comment by erikflowers** [comment]
I don't know. I have to pull the files down and put them in my development repo which is private, and then  get everything organized in this repo. I don't actually work with any of the files in this repo, they're just copied here for public consumption. Maybe I should change how I do that.

**Comment by erikflowers** [comment]
I'm adding SASS for 2.0 so downloaded your files manually since there some other SASS contributions and I need to plan how to build 2.0 a lot better and include the Less and Sass. Thanks for doing this, it will be a part of the 2.0.

**Comment by erikflowers** [comment]
Sass has been successfully added as a language in the 2.0-wip

**Pull request closed without merging**
