### PR TITLE
Lookups for Yahoo! Weather API

### PR DESCRIPTION
**Pull request by aphillipo**
Added .wi-condition-<condition-code> to icons and appropriate lookups.  

See https://developer.yahoo.com/weather/#codes for details of the codes.

You don't have to like it of course or merge it - just making you aware that this might be useful to someone.

### CODE REVIEW

**Comment by zakmac** [comment]
I have an open PR (#82 - Adding SASS support, refactoring Less for feature parity) which adds condition code mappings for Yahoo!, Forecast.io and OWM

**Comment by erikflowers** [comment]
Adding this through the 2.0 manually, I have downloaded your files in a ZIP.

**Comment by aphillipo** [comment]
Brilliant. This is such a useful addition to a great library. Ta.

**Comment by erikflowers** [comment]
Yahoo codes have been added to the 2.0-wip!

**Pull request closed without merging**
